version: '3.7'
services:
  mysql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=p1a2s3s4w5o6r7d
      - POSTGRES_DB=app
